name = "connect-share"
name_pretty = "Connect-Share"
icon = "applications-other"
global_search = true

[[entries]]
text = "Connect to share folder"
async = "kitty ~/.config/scripts/connect-share.sh"
icon = "applications-other"
action = ""
